name: road_sos
description: "RoadSOS — Emergency response app for road accidents."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.6

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Navigation
  go_router: ^17.2.3

  # Database
  sqflite: ^2.3.2
  path: ^1.9.0

  # Location & Maps
  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  flutter_map_cache: ^1.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_file_store: ^1.2.3
  latlong2: ^0.9.0

  # Sensors
  sensors_plus: ^7.0.0

  # Connectivity & Communication
  connectivity_plus: ^7.1.1
  battery_plus: ^6.1.0
  nearby_connections: ^4.1.0
  url_launcher: ^6.2.6

  # Background services
  flutter_background_service: ^5.0.2
  flutter_local_notifications: ^21.0.0

  # ML
  tflite_flutter: ^0.12.1

  # UI
  google_fonts: ^8.1.0
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.0

  # Permissions
  permission_handler: ^12.0.1

  # Storage
  shared_preferences: ^2.2.3
  share_plus: ^12.0.2
  path_provider: ^2.1.2
  speech_to_text: ^7.4.0

  # Utils
  intl: ^0.20.2
  uuid: ^4.4.0
  http: ^1.2.0
  flutter_dotenv: ^6.0.1

  # Firebase
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
